// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace FDML.Model
{
    public class ModelInput
    {
        [ColumnName("ID"), LoadColumn(0)]
        public float ID { get; set; }


        [ColumnName("CaseCode"), LoadColumn(1)]
        public string CaseCode { get; set; }


        [ColumnName("fkCode"), LoadColumn(2)]
        public string FkCode { get; set; }


        [ColumnName("JinE"), LoadColumn(3)]
        public float JinE { get; set; }


        [ColumnName("GuiDangDate"), LoadColumn(4)]
        public string GuiDangDate { get; set; }


        [ColumnName("DateSoure"), LoadColumn(5)]
        public string DateSoure { get; set; }


        [ColumnName("JinETypes"), LoadColumn(6)]
        public string JinETypes { get; set; }


    }
}
